export const skills = {
  programming: [
    { name: "C", icon: "SiC" },
    { name: "C++", icon: "SiCplusplus" },
    { name: "Java", icon: "FaJava" },
    { name: "Python", icon: "SiPython" },
    { name: "JavaScript", icon: "SiJavascript" },
    { name: "PHP", icon: "SiPhp" },
  ],
  webTech: [
    { name: "React.js", icon: "SiReact" },
    { name: "Node.js", icon: "SiNodedotjs" },
    { name: "Express.js", icon: "SiExpress" },
    { name: "MongoDB", icon: "SiMongodb" },
    { name: "MySQL", icon: "SiMysql" },
    { name: "Firebase", icon: "SiFirebase" },
  ],
  cloud: [
    { name: "AWS", icon: "SiAwsamplify" },
    { name: "Firebase", icon: "SiFirebase" },
    { name: "Docker", icon: "SiDocker" },
    { name: "Vercel", icon: "SiVercel" },
    { name: "Netlify", icon: "SiNetlify" },
    { name: "GitHub Actions", icon: "SiGithubactions" },
  ],
  tools: [
    { name: "Git", icon: "SiGit" },
    { name: "GitHub", icon: "SiGithub" },
    { name: "Postman", icon: "SiPostman" },
    { name: "Docker", icon: "SiDocker" },
    { name: "Linux", icon: "SiLinux" },
  ],
};

export const experiences = [
  {
    id: 1,
    title: "Technical Head",
    organization: "SKN IEEE Student Branch",
    period: "2024 - Present",
    description: "Leading technical initiatives and managing team of developers",
  },
  {
    id: 2,
    title: "Web Dev Lead",
    organization: "SKNISB",
    period: "2023 - 2024",
    description: "Led web development projects and mentored team members",
  },
  {
    id: 3,
    title: "Team Member",
    organization: "SKNISB",
    period: "2022 - 2023",
    description: "Contributed to various technical projects and events",
  },
  {
    id: 4,
    title: "Intern",
    organization: "Virtusky IT Pvt Ltd",
    period: "Summer 2023",
    description: "Worked on full-stack web applications and API development",
  },
];

export const projects = [
  {
    id: 1,
    title: "AGRI Bot",
    description: "Full-stack platform for agricultural assistance using AI and IoT sensors. Features real-time crop monitoring, disease detection, and expert consultation.",
    technologies: ["React.js", "Node.js", "MongoDB", "Express.js", "Firebase"],
    screenshots: ["/images/project1-1.png", "/images/project1-2.png", "/images/project1-3.png"],
    github: "#",
    live: "#",
  },
  {
    id: 2,
    title: "Donation Application",
    description: "Platform connecting donors with NGOs and individuals in need. Features secure payment integration, real-time tracking, and impact analytics.",
    technologies: ["React.js", "Firebase", "Stripe", "Tailwind CSS"],
    screenshots: ["/images/project2-1.png", "/images/project2-2.png"],
    github: "#",
    live: "#",
  },
  {
    id: 3,
    title: "Arova - Women's Health App",
    description: "Comprehensive health tracking application for women with period tracking, health tips, appointment scheduling, and community support.",
    technologies: ["React Native", "Node.js", "MongoDB", "Express.js"],
    screenshots: ["/images/project3-1.png", "/images/project3-2.png", "/images/project3-3.png"],
    github: "#",
    live: "#",
  },
  {
    id: 4,
    title: "Event Management Platform",
    description: "Dynamic event websites with registration, ticketing, and attendee management. Built for multiple college technical festivals.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Firebase"],
    screenshots: ["/images/project4-1.png"],
    github: "#",
    live: "#",
  },
];

export const achievements = [
  {
    id: 1,
    title: "State Level Project Competition - Second Rank",
    image: "/images/achievement1.jpg",
    rank: "2nd Rank",
    year: "2024",
  },
  {
    id: 2,
    title: "State Level Project Competition - Third Rank",
    image: "/images/achievement2.jpg",
    rank: "3rd Rank",
    year: "2024",
  },
  {
    id: 3,
    title: "Amrut Fest Project Competition - Second Rank",
    image: "/images/achievement3.jpg",
    rank: "2nd Rank",
    year: "2024",
  },
  {
    id: 4,
    title: "Jaihind Project Expo 2024 - First Rank",
    image: "/images/achievement4.jpg",
    rank: "1st Rank",
    year: "2024",
  },
  {
    id: 5,
    title: "Avishkar 2024 - Winner",
    image: "/images/achievement5.jpg",
    rank: "Winner",
    year: "2024",
  },
  {
    id: 6,
    title: "Project Paragon - Runner Up",
    image: "/images/achievement6.jpg",
    rank: "Runner Up",
    year: "2024",
  },
  {
    id: 7,
    title: "HackSphere - Runner Up",
    image: "/images/achievement7.jpg",
    rank: "Runner Up",
    year: "2024",
  },
  {
    id: 8,
    title: "TechMyst 2.0 - Winner",
    image: "/images/achievement8.jpg",
    rank: "Winner",
    year: "2024",
  },
  {
    id: 9,
    title: "PBL Pioneer 2025 - Third Rank",
    image: "/images/achievement9.jpg",
    rank: "3rd Rank",
    year: "2025",
  },
  {
    id: 10,
    title: "AI Ideation - Winner",
    image: "/images/achievement10.jpg",
    rank: "Winner",
    year: "2025",
  },
  {
    id: 11,
    title: "Srujan 2025 - First Rank",
    image: "/images/achievement11.jpg",
    rank: "1st Rank",
    year: "2025",
  },
  {
    id: 12,
    title: "TechTonic 2025 - Second Rank",
    image: "/images/achievement12.jpg",
    rank: "2nd Rank",
    year: "2025",
  },
  {
    id: 13,
    title: "Idezz 2025 - Runner Up",
    image: "/images/achievement13.jpg",
    rank: "Runner Up",
    year: "2025",
  },
  {
    id: 14,
    title: "Technovate 2025 - Third Rank",
    image: "/images/achievement14.jpg",
    rank: "3rd Rank",
    year: "2025",
  },
  {
    id: 15,
    title: "Convene 2025 - Winner",
    image: "/images/achievement15.jpg",
    rank: "Winner",
    year: "2025",
  },
];

export const contactInfo = {
  email: "parthghogare95@gmail.com",
  phone: "+91 9767942101",
  linkedin: "https://www.linkedin.com/in/parth-ghogare-16b793392/",
  github: "https://github.com/ParthGhogare09",
};
